apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: DataflowAttribute
metadata:
  name: app3-c50-p20-skyapp
spec:
  appName: app3-c50-p20-skyapp
  connections:
  - destinations:
    - constraints:
        latency: 793ms
      name: C27
    source: C1
  - destinations:
    - constraints:
        latency: 809ms
      name: C21
    - constraints:
        latency: 210ms
      name: C38
    source: C2
  - destinations:
    - constraints:
        latency: 370ms
      name: C19
    source: C3
  - destinations:
    - constraints:
        latency: 261ms
      name: C43
    source: C4
  - destinations:
    - constraints:
        latency: 514ms
      name: C40
    source: C5
  - destinations:
    - constraints:
        latency: 641ms
      name: C19
    source: C6
  - destinations:
    - constraints:
        latency: 824ms
      name: C44
    source: C7
  - destinations:
    - constraints:
        latency: 390ms
      name: C39
    source: C8
  - destinations:
    - constraints:
        latency: 779ms
      name: C29
    source: C9
  - destinations:
    - constraints:
        latency: 718ms
      name: C45
    source: C10
  - destinations:
    - constraints:
        latency: 770ms
      name: C13
    source: C11
  - destinations:
    - constraints:
        latency: 396ms
      name: C17
    source: C12
  - destinations:
    - constraints:
        latency: 508ms
      name: C15
    source: C13
  - destinations:
    - constraints:
        latency: 443ms
      name: C28
    source: C14
  - destinations:
    - constraints:
        latency: 653ms
      name: C24
    source: C15
  - destinations:
    - constraints:
        latency: 279ms
      name: C28
    source: C16
  - destinations:
    - constraints:
        latency: 255ms
      name: C39
    - constraints:
        latency: 938ms
      name: C36
    source: C17
  - destinations:
    - constraints:
        latency: 901ms
      name: C34
    source: C18
  - destinations:
    - constraints:
        latency: 338ms
      name: C29
    source: C19
  - destinations:
    - constraints:
        latency: 826ms
      name: C37
    source: C20
  - destinations:
    - constraints:
        latency: 494ms
      name: C24
    source: C21
  - destinations:
    - constraints:
        latency: 601ms
      name: C38
    source: C22
  - destinations:
    - constraints:
        latency: 712ms
      name: C41
    source: C23
  - destinations:
    - constraints:
        latency: 620ms
      name: C46
    source: C24
  - destinations:
    - constraints:
        latency: 484ms
      name: C33
    source: C25
  - destinations:
    - constraints:
        latency: 776ms
      name: C31
    - constraints:
        latency: 441ms
      name: C46
    source: C26
  - destinations:
    - constraints:
        latency: 694ms
      name: C40
    - constraints:
        latency: 779ms
      name: C34
    source: C27
  - destinations:
    - constraints:
        latency: 130ms
      name: C49
    source: C28
  - destinations:
    - constraints:
        latency: 783ms
      name: C34
    source: C29
  - destinations:
    - constraints:
        latency: 976ms
      name: C48
    source: C30
  - destinations:
    - constraints:
        latency: 921ms
      name: C37
    source: C31
  - destinations:
    - constraints:
        latency: 328ms
      name: C44
    source: C32
  - destinations:
    - constraints:
        latency: 981ms
      name: C43
    source: C33
  - destinations:
    - constraints:
        latency: 278ms
      name: C37
    source: C34
  - destinations:
    - constraints:
        latency: 529ms
      name: C50
    source: C35
  - destinations:
    - constraints:
        latency: 684ms
      name: C42
    source: C36
  - destinations:
    - constraints:
        latency: 169ms
      name: C39
    source: C37
  - destinations:
    - constraints:
        latency: 483ms
      name: C44
    source: C38
  - destinations:
    - constraints:
        latency: 868ms
      name: C49
    source: C39
  - destinations:
    - constraints:
        latency: 820ms
      name: C44
    source: C40
  - destinations:
    - constraints:
        latency: 197ms
      name: C43
    source: C41
  - destinations:
    - constraints:
        latency: 919ms
      name: C48
    source: C42
  - destinations:
    - constraints:
        latency: 914ms
      name: C50
    source: C43
  - destinations:
    - constraints:
        latency: 975ms
      name: C48
    source: C44
  - destinations:
    - constraints:
        latency: 972ms
      name: C50
    source: C45
  - destinations:
    - constraints:
        latency: 280ms
      name: C47
    source: C46
  - destinations:
    - constraints:
        latency: 627ms
      name: C49
    source: C47
  - destinations:
    - constraints:
        latency: 223ms
      name: C50
    source: C48
  - destinations:
    - constraints:
        latency: 207ms
      name: C50
    source: C49
