apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: DataflowAttribute
metadata:
  name: app7-c20-p20-skyapp
spec:
  appName: app7-c20-p20-skyapp
  connections:
  - destinations:
    - constraints:
        latency: 731ms
      name: C20
    source: C1
  - destinations:
    - constraints:
        latency: 400ms
      name: C10
    source: C2
  - destinations:
    - constraints:
        latency: 562ms
      name: C8
    source: C3
  - destinations:
    - constraints:
        latency: 503ms
      name: C10
    source: C4
  - destinations:
    - constraints:
        latency: 149ms
      name: C19
    source: C5
  - destinations:
    - constraints:
        latency: 211ms
      name: C17
    source: C6
  - destinations:
    - constraints:
        latency: 809ms
      name: C13
    source: C7
  - destinations:
    - constraints:
        latency: 734ms
      name: C12
    source: C8
  - destinations:
    - constraints:
        latency: 367ms
      name: C20
    source: C9
  - destinations:
    - constraints:
        latency: 569ms
      name: C12
    - constraints:
        latency: 755ms
      name: C13
    source: C10
  - destinations:
    - constraints:
        latency: 574ms
      name: C15
    source: C11
  - destinations:
    - constraints:
        latency: 916ms
      name: C19
    source: C12
  - destinations:
    - constraints:
        latency: 738ms
      name: C15
    source: C13
  - destinations:
    - constraints:
        latency: 411ms
      name: C18
    source: C14
  - destinations:
    - constraints:
        latency: 118ms
      name: C20
    - constraints:
        latency: 719ms
      name: C17
    source: C15
  - destinations:
    - constraints:
        latency: 716ms
      name: C19
    source: C16
  - destinations:
    - constraints:
        latency: 511ms
      name: C20
    - constraints:
        latency: 113ms
      name: C19
    source: C17
  - destinations:
    - constraints:
        latency: 744ms
      name: C19
    source: C18
  - destinations:
    - constraints:
        latency: 383ms
      name: C20
    source: C19
