apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: app8-c10-p20-skyapp
spec:
  appConfig:
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: vs3
    name: C1
  - constraints:
      locationConstraints:
      - providerType: edge
      virtualServiceConstraints:
      - virtualServiceName: vs1
    name: C2
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: vs3
    name: C3
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: vs1
    name: C4
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
      virtualServiceConstraints:
      - virtualServiceName: vs2
    name: C5
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
      virtualServiceConstraints:
      - virtualServiceName: vs2
    name: C6
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: vs5
    name: C7
  - constraints:
      locationConstraints:
      - providerType: edge
      virtualServiceConstraints:
      - virtualServiceName: vs3
    name: C8
  - constraints:
      locationConstraints:
      - providerType: edge
      virtualServiceConstraints:
      - virtualServiceName: vs3
    name: C9
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
      virtualServiceConstraints:
      - virtualServiceName: vs4
    name: C10
  appName: app8-c10-p20-skyapp
  namespace: default
