---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVyakNDQXhhZ0F3SUJBZ0lSQUtYK29VQWVseTdCNDZNT1N0NU9aaDh3RFFZSktvWklodmNOQVFFTEJRQXcKYnpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU0l3SUFZRFZRUUxEQmwxWW5WdQpkSFZBWlhOdUxXczRjeTB4SUNoVlluVnVkSFVwTVNrd0p3WURWUVFERENCdGEyTmxjblFnZFdKMWJuUjFRR1Z6CmJpMXJPSE10TVNBb1ZXSjFiblIxS1RBZUZ3MHlOREF4TVRjd05EQXdORE5hRncwek5EQXhNVGN3TkRBd05ETmEKTUc4eEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEVpTUNBR0ExVUVDd3daZFdKMQpiblIxUUdWemJpMXJPSE10TVNBb1ZXSjFiblIxS1RFcE1DY0dBMVVFQXd3Z2JXdGpaWEowSUhWaWRXNTBkVUJsCmMyNHRhemh6TFRFZ0tGVmlkVzUwZFNrd2dnR2lNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJqd0F3Z2dHS0FvSUIKZ1FESld4UVg5UHRqNVByazBUeFg3bnNReElscUhFZlE5cW5DYXhwN1o2MFZhNllQTlVTU3ZnTFZwN2FNTWYyUApMcS9ZUkdoYUI4d21oQTd1NHc4Q0U5TVpUWmVwTmQ0aU02MmVHWnJ4ZjNEUG1aUlMvdWgyUytwNVA4ZzUxbS9CCmd6dGE2TWpDc2VIUjRndDRWcVpoQUFTNDRINk9DWm5sa3hUQXZDUXFxanJkU3ZuNWgzVEdnUEcvb0k3d04wQkkKV3RVd1NFL0c3c2JHNlAvRjZGbEpjN25hZzV4NE0xaVRSblhENVdreHlOU0ROdDVKNDc2Z2k0d0lrVXVkSmZaZgpTdUcxYTByWjRRM2Y0WWhvdU93eUpVZjFPRy9XUzFhQllTQWY2cXJCemc2VUhiemV2dzFWNktmNTFQWEVqMjVhClBHWGdIWkJKQlIrelJualVkTi9UcjJqbUhwWjlHY1RsUzgweVkzbFFSSXF2NXJRNDJHck9PZXhtNklKRHpCakIKMXp4cDN5RDZCdnlMNktEaEROWGZFaXpLSVpoZmg1ZitHVFExNDYrSWN4YWpuUDBQcEZhM3Q3S3BMUlQ4VkRwTAptdkd2Y2RvaFJlc2dXOEw4RFF5R0dXMDFDbWp2VjdRU000YmV5YUlmN010Y054aG1OeE03NW9uZHJJcFpTQjhqCkRCc0NBd0VBQWFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXcKSFFZRFZSME9CQllFRkVTKzhlQXZtcFBac3lQZHFzaGw5QUlqRy8wVk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpnUUFMWEFGdTFEWE9JS2ZZU2JkejhuTzBlSnBMNjd0UTdKVzZlQ2xTRlNjRkIvazhOYlBaMTZjdGN0a01NRkF2ClAxU0trcEVhWmtPeVFHWktYSFhtQkEzZ0FyUm94Z2tIUFUzRm5jSVpNNHYvemd4Wk1vVkxxai91aUp6MkxlRmIKeGYwaVJmY1pRNnp4VFlERkxBb20vMXIrcnQxQVlPektnVTBWMVJ6alpLOVM5ZllMN25SVDFHMzlHcTErY3ZxNwpSQVh1cWxzb25aVHM1c0wyeHVBNlk2bEk2OTYwMmJjeWh2aSsvWGZiZXl2R3pTTUl2TTc1TmlGbVdwV0JlTjlMClppTmhleWFUcERab1lFeU9wQW8wYzlDN0VNcFBhUTNrN0JvMy9HM0dxVVVJeDlSaGNMSGdFZjNFTXBxZEg2Z3EKV1poTkFUdWNVK0oxL3ZHYzRyQ2RxTGlpem12eURMYjJmQ3o0cUNrVkwyVGV4dkJGN240ancwVzRpdS9obVU2cQo1VEZnQUpnZzEyWmtHcmYxcXpUbmVuTi9PbmpzcWF1RjV3VXlsc3h1N2xtZER6ZnBsYzNFT2hUQjlKbGx1TTN2CnpZbmlEekwveDdNOG1Oc3NvQU9QK3BNeExaYnlBMFpMcUhkV1VYVFhQZXZST3BYLy85a3JDT3JlMlQrRnpBWnIKWTRZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://172.17.0.1:9443/mutate-apps-v1-deployment
  failurePolicy: Fail
  name: mdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - deployments
  sideEffects: None