apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: skyapp1
spec:
  appConfig:
  - constraints:
      locationConstraints:
      - providerType: edge # near-the-edge, cloud
        # providerName: # aws, azure, gcp, ...
        # region: # us-west, us-east, ...
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c1
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c2
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c3
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c4
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c5
  appName: skyapp1
  # namespace: default
