# permissions for end users to view xkyxrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: skycluster-manager
    app.kubernetes.io/managed-by: kustomize
  name: core-skyxrd-viewer-role
rules:
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - xkyxrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - xkyxrds/status
  verbs:
  - get
