# permissions for end users to view dataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: skycluster-manager
    app.kubernetes.io/managed-by: kustomize
  name: core-dataflow-viewer-role
rules:
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - dataflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - dataflows/status
  verbs:
  - get
