---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - skyxrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - skyxrds/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - skyxrds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.skycluster.io
  resources:
  - ilptasks
  - skyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster.io
  resources:
  - ilptasks/finalizers
  - skyclusters/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster.io
  resources:
  - ilptasks/status
  - skyclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies
  - deploymentpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/finalizers
  - deploymentpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/status
  - deploymentpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps
  - skyk8s
  - skysetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps/finalizers
  - skyk8s/finalizers
  - skysetups/finalizers
  verbs:
  - update
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps/status
  - skyk8s/status
  - skysetups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - xrds.skycluster.io
  resources:
  - skyk8sclusters
  verbs:
  - delete
  - patch
  - update
