---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - ilptasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - ilptasks/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - ilptasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - providerattributes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - providerattributes/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - providerattributes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - skyapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - skyapps/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - skyapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - virtualservices/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster-manager.savitestbed.ca
  resources:
  - virtualservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.skycluster-manager.savitestbed.ca
  resources:
  - dataflowattributes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.skycluster-manager.savitestbed.ca
  resources:
  - dataflowattributes/finalizers
  verbs:
  - update
- apiGroups:
  - policy.skycluster-manager.savitestbed.ca
  resources:
  - dataflowattributes/status
  verbs:
  - get
  - patch
  - update
