# This rule is not used by the project skycluster-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to svc.skycluster.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: skycluster-manager
    app.kubernetes.io/managed-by: kustomize
  name: svc-skyprovider-viewer-role
rules:
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyproviders/status
  verbs:
  - get
