apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: skyapp1
spec:
  appConfig:
  - constraints:
      locationConstraints:
      # Should add permitted and
      # required locations constraints
      - providerType: cloud # near-the-edge, cloud
        providerName: savi # aws, azure, gcp, ...
        # region: # us-west, us-east, ...
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c1
  - constraints:
      locationConstraints:
      - providerType: cloud
        providerName: savi 
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c2
  - constraints:
      locationConstraints:
      - providerType: cloud
        providerName: savi 
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c3
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
        providerName: savi 
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c4
  - constraints:
      locationConstraints:
      - providerType: near-the-edge
        providerName: savi 
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: c5
  appName: app1
  # namespace: default
