apiVersion: svc.skycluster.io/v1alpha1
kind: SkyProvider
metadata:
  name: skysetup-zone-1-test
  labels:
    skycluster.io/ext-ProjectV3-identity-v1alpha1: 1e1c724728544ec2a9058303ddc8f30b
    skycluster.io/ext-RouterV2-networking-v1alpha1: 0033d21d-56e2-4cde-9755-de6153167017
    skycluster.io/ext-SubnetV2-networking-v1alpha1: ext-net
    skycluster.io/managed-by: skycluster
spec: 
  providerGateway:
    vpcCidr: 10.10.1.0/24
    flavor: 8vCPU-32GB
    # overlay:
    #   host: 
    #   port:
    #   token:
    # publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQz3
  monitoring:
    protocol: ssh
    checkCommand: |
      free -h | grep Mem
      exit 0
    failureAction: recreate
    schedule:
      retries: 10
      interval: 15
  providerRef:
    providerName: os
    providerRegion: scinet
    providerZone: zone-1