apiVersion: core.skycluster.savitestbed.ca/v1alpha1
kind: Dataflow
metadata:
  labels:
    app.kubernetes.io/name: dataflow
    app.kubernetes.io/instance: dataflow-sample
    app.kubernetes.io/part-of: skycluster-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: skycluster-manager
  name: dataflow-sample
spec:
  # TODO(user): Add fields here
