apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: app1-c5-p20-skyapp
spec:
  appConfig:
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: C1
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: C2
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: C3
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: C4
  - constraints:
      locationConstraints:
      - providerType: cloud
      virtualServiceConstraints:
      - virtualServiceName: skyk8scluster
    name: C5
  appName: app1-c5-p20-skyapp
  # namespace: default
