apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: DataflowAttribute
metadata:
  name: app10-20-dataflow
spec:
  appName: app10-20-skyapp
  connections:
    - source: frontend
      destinations:
        - name: backend
          constraints:
            latency: 500ms
    - source: backend
      destinations:
        - name: payment
          constraints:
            latency: 500ms
