apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: app9-20-skyapp
spec:
  appName: app9-20-skyapp
  namespace: default
  appConfig:
    - name: frontend
      constraints:
        locationConstraints:
          - providerType: cloud
        virtualServiceConstraints:
          - virtualServiceName: vs1
    - name: backend
      constraints:
        locationConstraints:
          - providerType: cloud
        virtualServiceConstraints:
          - virtualServiceName: vs2
    - name: payment
      constraints:
        locationConstraints:
          - providerType: cloud
        virtualServiceConstraints:
          - virtualServiceName: vs3
