---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5akNDQXpLZ0F3SUJBZ0lSQUtuT0tJRWpNdGdFWUVodkR5RnRRaEF3RFFZSktvWklodmNOQVFFTEJRQXcKZlRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU2t3SndZRFZRUUxEQ0IxWW5WdQpkSFZBWlhOdUxYTnJlV05zZFhOMFpYSXRNU0FvVldKMWJuUjFLVEV3TUM0R0ExVUVBd3duYld0alpYSjBJSFZpCmRXNTBkVUJsYzI0dGMydDVZMngxYzNSbGNpMHhJQ2hWWW5WdWRIVXBNQjRYRFRJME1EZ3dNVEF4TlRneE1Wb1gKRFRNME1EZ3dNVEF4TlRneE1Wb3dmVEVlTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQgpNU2t3SndZRFZRUUxEQ0IxWW5WdWRIVkFaWE51TFhOcmVXTnNkWE4wWlhJdE1TQW9WV0oxYm5SMUtURXdNQzRHCkExVUVBd3duYld0alpYSjBJSFZpZFc1MGRVQmxjMjR0YzJ0NVkyeDFjM1JsY2kweElDaFZZblZ1ZEhVcE1JSUIKb2pBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVk4QU1JSUJpZ0tDQVlFQXUvUjNDazZiUGtxcm9nUEUvaEl1WDM1Twp2L1FERFN5TUlDN0JxMlJXRmZ1ZUYzQTNFUEgwQVkweGRwMmhXS2gvT2JnYzhMeE5NbE1yY1l4bWptZkdnVGJuCll2U1hJZ0FJMjdaTENmbmpoSXFTbHlOY3FnaCtVenNwL2V3enRUWXVSRnpseTAxT29pcGJqTnJIRTY3WmdvNXoKTzZvY1VGK3ZaWC9EUk85ZGNEKzVIc2xIUkxWNnBBV2hyQ2ZDQ1lZSTlWTWpCMW9UMm5zTUkyWS8vTGNTNGJWRgozVndkeXVvZTcvZmk5b2d2QWU5b3dtbFBEOHdTdmV5dWhRL1hUb0NtUXAyWGdFM09EekFtU1FIOWFJbXJkNVhkCldNZnVkUXk0aFlVZWNQMUdON3JCdmdkcmZqQ1NMOXF3NzVNc3Y1T3FpN01WSmNtVWpFNVBpY0ZKODI0eCtZdUsKVXYzWlVnb0Z0bU5JYzB5NlY2V0ZlK1FXR2RPTEhKa2huMHNsQnFiR1lYdE9NVmRyalBld1YzYy9aKzRQTzNUNApZbzNrMUx2ODF5LzhDdVBjT2xWbk9JanN0ZUVycUpyODlsZll6TjVhSEVoNmFndTdLNGVHaHJMUTIxTkRWZWV5CnY2WUxDRC9QeVZTV0xIZEQ1YmhzMndnZkZUVlpMWUE2cXM0VGFoWDlBZ01CQUFHalJUQkRNQTRHQTFVZER3RUIKL3dRRUF3SUNCREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJUL1lDZjNZbHBuK01seApPZ3ZnY1BGdEt6bEo3REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBUnNaTGYxR1djZXJVcGt6dHM1QTlwRWhjCkdPbXlHM2JleUV1aFRtZmt4WVhURVpRWFM4MjJiK2dod0xKRXFERkcwUWhEdHlUYk1aMVhmemJNUUczV01PL0oKVjNibnY0UUEvYVJ0SmRvOHlHRUFqei9zMVloWGFFRy80S1A5N05zNWg4U2lickhrNHJpeHI4dGlTcFkrQzN5ZwptSzRNbmQyUVJpLzg5OW5ZaEN0RURzK3JDdUtyV1pXdS9hUjlNU1J3WlpmU3lDemllc3lkMnVNWHNpMFpidGJmCjFueHh5MjJ6QllLajl0UEIzVUhBQVh5UnVySlBScDRPUVE4bm5kTzk0dkxuYW9XOGJVMGQwWVAwUlRTQkpmZngKUGF1WjF6TlllcTRkNU16NzdrdlFJbDhqbFBRcyt4V2kyRFRVNm02M05iSTFEd2p3QkFmQWtHVXhYMkUwMWdOVApPNms3d3J3aUtXdWkxdGluQU1UL0VmVDMvVjlSRldKajlJOEV5WGQ4V1hROU9XYXZBSlNJWnNSZG1QMDRuYnRPClM3eHI0Z0dpamt1ZDJ3OC81MWJBU1Y2bXRoaVVvd1MweWEySmEzZzFITVY1TXJHclVYQWUxYkdMc1ZBUjlSZlUKa3hTcU95a0RRa2dnSktXM2syd3FxNUZJTmppclpvQ2xsSVhWcjR5cAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://172.17.0.1:9443/mutate-apps-v1-deployment
  failurePolicy: Fail
  name: mdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - deployments
  sideEffects: None