apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5akNDQXpLZ0F3SUJBZ0lSQU1QTHZLN0xCWk5oc3dFM3p6ZVZ1dkV3RFFZSktvWklodmNOQVFFTEJRQXcKZlRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU2t3SndZRFZRUUxEQ0IxWW5WdQpkSFZBWW14MVpXTnNkWE4wWlhJdFpHVjJNU0FvVldKMWJuUjFLVEV3TUM0R0ExVUVBd3duYld0alpYSjBJSFZpCmRXNTBkVUJpYkhWbFkyeDFjM1JsY2kxa1pYWXhJQ2hWWW5WdWRIVXBNQjRYRFRJMU1ESXlNREUzTVRneU0xb1gKRFRNMU1ESXlNREUzTVRneU0xb3dmVEVlTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQgpNU2t3SndZRFZRUUxEQ0IxWW5WdWRIVkFZbXgxWldOc2RYTjBaWEl0WkdWMk1TQW9WV0oxYm5SMUtURXdNQzRHCkExVUVBd3duYld0alpYSjBJSFZpZFc1MGRVQmliSFZsWTJ4MWMzUmxjaTFrWlhZeElDaFZZblZ1ZEhVcE1JSUIKb2pBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVk4QU1JSUJpZ0tDQVlFQTB2WlMvWjFlU1BNQVFyZ3BzZXNEbjJqSQpHVHUxQ0psaDlzSG5RWnRUSUZabWtWMDZnTGpsdlJFN2pHdk1Rb0JrL3EySmRoYkhzdGtyNGlveXNnRW1oQ0tsCkZ6akFNYmdEcDU4V1NDa3d4ZWEwczBIL3JtR3BPWlZwalpreFZidkcwNHRtYktiR1NtbmRRWWlrQnJzR2Y4RncKbWhzeU93c3owYXFsS0JVK0pGR2hhSjdNQ2hSTXdValYwRzNibzF3L3U2S3dCT1pCZjBYa3Bod0srR2k0YkRvaQpudFFRN0RHU0toMC9LaFlQSFNGK1hvbUpjTU1BNGFZZkRyVlkvVVR0aWlRLzhiYUJuT0pyeGNIRjJUMkRaaG1sClRSYlpEVHErWVplNmprZ2xHZjVTU3FjWXVUS2JkQUI5Q2t6UUtyenVtTzdHSXpBcG5uVzFlelZkY0Y2aFJOUkoKQ1g1bk1ZakNkSTVzSGZTWlovRi9NQXlxNllZa05YZGsvbDlBUE1IWWVCaG5haVJFWVVQYnpMZGZtaUlEcVlkeAozV2p1UTFiWkpGbnhyUEhOM3BjVHZzVFhzbHBNZGxrVFZ5bnN2SXZIT3B3V1hoa2s1NWNpYzZGMUpjRksxQ3J4CmxPOXllZnZsZGxhYWtYMlYrTVcwUm4wMFpvODB2WTNnTGVGVmxZblBBZ01CQUFHalJUQkRNQTRHQTFVZER3RUIKL3dRRUF3SUNCREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJTc1I2UnQ4UU5zYmxHSwpVV2J1NS9vYnFFMll5VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBaXgranVadTVvdC9RR3czYmpORGdQbEorCll0Nk5BTld5cjFVSjNHQ0tocHdtVHNjbldWYnhSTmwxS0FDNk5tU01oVU5yWkNBODN4NWVkV0dwT1N2WlRaMG4KMXR1dW45MEJPcTVYQ1dmb0wxVFVxU1ZRQjhWWklSTGU3QzFmRUNIeXBvNDdBdEVxb1ZHNnJreWdRUmxjZDZJZgpiZDhGdWNXbG45QjZQa0lsaGpjN1AzTDFQMUFjdThQUjVzc1N1WFBoV1BiZzVaSXNYVXZORjBuOVh3dXpsRVpaCkt5bFpGTStyZCt5OXU4cFV4b2RaWkZ4dUdRM1NQWEk2SGFMbXRaUDNhUER3WGlud0dEczNGQjdqQ2dYd1pZU1AKUWd3VFNqUWdqNGVobzZjN09zOUtCTmZQYmVZcFE5d01NRFRjRnRRSE5xNEtrQVJrZTBTanZ5dGcxK2g5ZG5OSAp6TWlzZWtVNmRoakh2emErK01CYk9SWWp0RDlmUWlhajYybXJkMmNJdzlVQVdNenRlSFo1ZFRKWHpKdmE1bktsCmpXREpnK3BnQkhpOHJIRmJ6cG01NUpOaS9nZUJwVDRwdE1SOUxFSHZ4ZmhXejVUUWZmWWNEbCtEVUNmd1pxZUMKa1dDaU9BckJtbEZPY0NZbEtWSXZxdUpHcmt3L3NYTjZ4NUFJU2Y0egotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://172.17.0.1:9443/mutate-apps-v1-deployment
  failurePolicy: Fail
  name: mdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: None
