apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: skyapp-sample
spec:
  appName: my-skyapp1
  namespace: default
  appConfig:
    - name: frontend
      # following constraint will be honored and 
      # if any of the constraints are not met, the deployment will fail
      constraints:
        locationConstraints:
          # This is a composite constraints
          # 
          # providerType: cloud ensure 'frontend' is deployed on a cloud provider
          # TODO: What if I want to ensure the 'frontend' is deployed across all providers with typed [cloud]?
          # Currently, one needs to specify the providerName and region and providerType 
          # for all (provider, region, type) combinations. Perhaps another approach is:
          # TODO: Maybe we can add a new field 'mode' with value 'all/any' 
          #   'all' means all providers with type [cloud] and 
          #   'any' means even one provider with type [cloud] is ok
          # 
          - # providerName: gcp
            # This ensures the optimizer will only select gcp providers
            # region: us-west1
            # This ensures the optimizer will only select gcp providers in us-west1 region
            providerType: cloud
            # providerType: edge
            # This ensures the optimizer will only select gcp providers in us-west1 of type edge
        virtualServiceConstraints:
          - virtualServiceName: vs1
    - name: backend
      constraints:
        locationConstraints:
          - providerType: cloud
          # - providerType: near-the-edge
        virtualServiceConstraints:
          - virtualServiceName: vs2
    - name: payment
      constraints:
        locationConstraints:
          - providerType: cloud
        virtualServiceConstraints:
          - virtualServiceName: vs3
---
apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: DataflowAttribute
metadata:
  name: dataflow-sample
spec:
  appName: my-skyapp1
  connections:
    - source: frontend
      destinations:
        - name: backend
          constraints:
            latency: 500ms
    - source: backend
      destinations:
        - name: payment
          constraints:
            latency: 500ms
---
