apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: SkyApp
metadata:
  name: skyapp-sample
spec:
  appName: my-skyapp1
  namespace: default
  appConfig:
    - name: frontend
      constraints:
        locationConstraints:
          - providerName: provider-1 # aws-west1, gcp-east1
            region: west1 # east, west, north, south
            providerType: cloud # near-the-edge, Cloud
          - providerName: provider-1 # aws-west1, gcp-east1
        virtualServiceConstraints:
          - virtualServiceName: vs-1
    - name: backend
      constraints:
        locationConstraints:
          - providerName: provider-2
        virtualServiceConstraints:
          - virtualServiceName: vs-1
    - name: payment
      constraints:
        locationConstraints:
          - providerName: provider-3
        virtualServiceConstraints:
          - virtualServiceName: vs-1
---
apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
kind: DataflowAttribute
metadata:
  name: dataflow-sample
spec:
  appName: my-skyapp1
  connections:
    - source: frontend
      destinations:
        - name: backend
          constraints:
            latency: 10ms
    - source: backend
      destinations:
        - name: payment
          constraints:
            latency: 10ms
---
# ################ VIRTUAL SERVICES ################
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: VirtualService
# metadata:
#   name: virtualservice-sample
# spec:
#   name: vs1
#   vservicecosts:
#     - providerName: aws-east1
#       cost: "100"
#     - providerName: aws-west1
#       cost: "200"
# ---
# ################ PROVIDERS ################
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: Provider
# metadata:
#   name: aws-east1
# spec:
#   name: aws
#   region: east1
#   zone: default
#   type: cloud
# ---
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: Provider
# metadata:
#   name: aws-west1
# spec:
#   name: aws
#   region: west1
#   zone: default
#   type: cloud
# ---
# ################ ProviderAttribute ################
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: ProviderAttribute
# metadata:
#   name: pattr-aws-east1-aws-west1
# spec:
#   providerReference:
#     name: aws-east1
#     namespace: default
#   providerMetrics:
#     - dstProviderName: aws-west1
#       latency: 10ms
#       egressDataCost: "100"
# ---
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: ProviderAttribute
# metadata:
#   name: pattr-aws-west1-aws-east1
# spec:
#   providerReference:
#     name: aws-west1
#     namespace: default
#   providerMetrics:
#     - dstProviderName: aws-east1
#       latency: 10ms
#       egressDataCost: "100"
# ---
# apiVersion: core.skycluster-manager.savitestbed.ca/v1alpha1
# kind: ILPTask
# metadata:
#   name: ilptask-sample
# spec:
#   problemDefinition: |
#     import numpy as np
# ---
